name: BD-Spleef
version: 1.0.3
api-version: 1.15
authors: [Naruse, 12emin34]
main: fr.naruse.spleef.main.SpleefPlugin
softdepend: [Vault, PlaceholderAPI, HolographicDisplays]
commands:
  spleef:
    description: All commands for Spleef
description: A Spleef plugin for Bukkit, optimized for BalkanDestruction.
