name: BD-Spleef
version: 1.0.7
api-version: 1.16
authors: [Naruse, 12emin34]
main: fr.naruse.spleef.main.SpleefPlugin
softdepend: [Vault, PlaceholderAPI, HolographicDisplays, WorldEdit]
commands:
  spleef:
    description: All commands for Spleef
description: A Spleef plugin for Bukkit, optimized for BalkanDestruction.
